[project]
name = "telegram-bot-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-settings>=2.8.1",
    "python-telegram-bot>=22.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
]
